routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/home', 'HomeController@index');
//////////////////
Route::get('/', 'IndexController@index')->name('home');

Route::resource('tag', 'TagController');
Route::resource('category', 'CategoryController');
Route::resource('question', 'QuestionController');
Route::resource('answer', 'AnswerController');
Route::resource('comment', 'CommentController');

Route::resource('user', 'UserController');

Route::patch('answer/{answer}/votePositive', 'AnswerController@votePositive')->name('answer.positive');
Route::patch('answer/{answer}/voteNegative', 'AnswerController@voteNegative')->name('answer.negative');
Route::patch('question/{question}/votePositive', 'QuestionController@votePositive')->name('question.positive');// not completed
Route::patch('question/{question}/voteNegative', 'QuestionController@voteNegative')->name('question.negative');// not completed

Route::patch('answer/{answer}/bestAnswer', 'AnswerController@bestAnswer')->name('answer.best');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected $fillable = [
        'user_id', 'name', 'title', 'content', 'vote', 'closed', 'category_id'
    ];

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withPivot('question_id', 'tag_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Question;
use App\Tag;
use Illuminate\Http\Request;

class QuestionController extends Controller
{
    public function __construct()
    {
        $this->middleware('throttle:1,0.1')->only('voteNegative', 'votePositive');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = Question::all();

        return view('question.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::pluck('name', 'id');
        $tags = Tag::pluck('name', 'id');

        return view('question.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $inputs = $request->all();

        if (auth()->check()) {
            $inputs['name'] = auth()->user()->name;
            $inputs['user_id'] = auth()->user()->id;
        } else $inputs['name'] = $inputs['name'] . ' (کاربر مهمان) ';

        $question = Question::create($inputs);
        $question->tags()->sync($inputs['tag_id']);

        return redirect()->back();

        ///////////////add instant new tag
//        $inputs = $request->all();
//        dd($inputs);
//        $tags[] = $inputs['tag_id'];
////        dd($tags);
//        $i = 0 ;
//        foreach ($tags as $key => $tag){
//            $question = Tag::create(['name' => "$tag[$i]", 'user_id' => '1']);
////            dd($tag[$i]);
//            $inputs['tag_id'] = Tag::where('name', "$tag[$i]")->pluck('id');
//            $i++;
//        }
//        $question = Question::create($inputs);
//        $question->tags()->sync($inputs['tag_id']);
//        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {

        return view('question.show', compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        $categories = Category::pluck('name', 'id');
        $tags = Tag::pluck('name', 'id');

        return view('question.edit', compact('question', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Question $question
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question)
    {
        $this->authorize('edit-question', $question);

        $inputs = $request->all();

        $question->update($inputs);
        $question->tags()->sync($inputs['tag_id']);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        $this->authorize('is-admin');

        $question->delete();

        return redirect()->back();
    }

    public function votePositive(Question $question)
    {
        $question->update(['vote' => $question['vote'] + 1]);
        if (count($question['user_id'])) {
            $question_vote = $question->user()->pluck('vote');
            $question->user()->update(['vote' => $question_vote[0] + 1]);
        }

        return redirect()->back();
    }

    public function voteNegative(Question $question)
    {
        $question->update(['vote' => $question['vote'] - 1]);
        if (count($question['user_id'])) {
            $question_vote = $question->user()->pluck('vote');
            $question->user()->update(['vote' => $question_vote[0] - 1]);
        }

        return redirect()->back();
    }
}

resources/views/question/create.blade.php
@extends('layouts.layout')
@section('content')

    @if(Auth::check())
        <div>
                            <span>
                                وارد شده با نام کاربری:
                            </span>
            <span>{{ auth()->user()->name }}</span>
            <span>/</span>
            <span>
                            <a href="#"
                               onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            خروج
                            </a>
                            <form id="logout-form" action="/logout" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                            </span>
        </div>
        {!! Form::open(['route'=>['question.store']]) !!}
    @else
    {!! Form::open(['route'=>['question.store']]) !!}

    <!-- فیلد نام شما: -->
    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
        {!! Form::label('name', 'نام شما:') !!}
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
        @if ($errors->has('name'))
            <span class="help-block"><strong>{{ $errors->first('name') }}</strong></span>
        @endif
    </div>
    <span>
                                <a href="{{ route('register') }}">
                                ثبت نام
                                </a>
                        </span>
    <span>/</span>
    <span>
                                <a href="{{ route('login') }}">
                                ورود
                                </a>
                        </span>
    @endif

    @include('question.fields')

    {!! Form::close() !!}

@endsection

resources/views/question/edit.blade.php
@extends('layouts.layout')
@section('content')

    {!! Form::model($question, ['route'=>['question.update', $question->id ], 'method' => 'patch', 'files' => true ]) !!}

    <!-- فیلد نام شما: -->
    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
        {!! Form::label('name', 'نام شما:') !!}
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
        @if ($errors->has('name'))
            <span class="help-block"><strong>{{ $errors->first('name') }}</strong></span>
        @endif
    </div>

    @include('question.fields')

    {!! Form::close() !!}
	
@endsection

resources/views/question/fields.blade.php
<!-- فیلد دسته -->
<div class="form-group {{ $errors->has('category_id') ? ' has-error' : '' }}">
    {!! Form::label('category_id', 'دسته') !!}
    {!! Form::select('category_id', $categories, null, ['class' => 'form-control']) !!}
    @if ($errors->has('category_id'))
        <span class="help-block"><strong>{{ $errors->first('category_id') }}</strong></span>
    @endif
</div>
<!-- فیلد عنوان -->
<div class="form-group {{ $errors->has('title') ? ' has-error' : '' }}">
    {!! Form::label('title', 'عنوان') !!}
    {!! Form::text('title', null, ['class' => 'form-control']) !!}
    @if ($errors->has('title'))
        <span class="help-block"><strong>{{ $errors->first('title') }}</strong></span>
    @endif
</div>
<!-- فیلد محتوا -->
<div class="form-group {{ $errors->has('content') ? ' has-error' : '' }}">
    {!! Form::label('content', 'محتوا') !!}
    {!! Form::textarea('content', null, ['class' => 'form-control', 'id'=>'editor1']) !!}
    @if ($errors->has('content'))
        <span class="help-block"><strong>{{ $errors->first('content') }}</strong></span>
    @endif
</div>
<!-- فیلد برچسب ها -->
<div class="form-group {{ $errors->has('tag_id[]') ? ' has-error' : '' }}">
    {!! Form::label('tag_id[]', 'برچسب ها') !!}
    {!! Form::select('tag_id[]',$tags , (isset($question))?$question->tags:null, ['class' => 'form-control select2', 'multiple' => 'multiple']) !!}
    @if ($errors->has('tag_id[]'))
        <span class="help-block"><strong>{{ $errors->first('tag_id[]') }}</strong></span>
    @endif
</div>

<button type="submit" class="btn btn-success">ثبت</button>
<a href="{{ route('question.index') }}" class="btn btn-primary">صفحه نخست</a>

resources/views/question/index.blade.php
@extends('layouts.layout')
@section('content')

    <a href="{{ route('question.create') }}" class="btn-primary btn">سوال جدید</a>

    <table class="table table-hover">
        <thead>
        <tr>
            <th>نویسنده</th>
            <th>عنوان</th>
            <th>محتوا</th>
            <th>دسته</th>
            <th>برچسب ها</th>
            <th>عملیات</th>
        </tr>
        </thead>
        <tbody>
        @foreach($questions as $question)
            <tr>
                <td>{{ $question->name }}</td>
                <td><a href="{{ route('question.edit', $question->id) }}">{{ $question->title }}</a></td>
                <td style="max-width: 500px">{{ $question->content }}</td>
                <td>
                    <a href="{{ route('category.edit', $question->category->id) }}"> {{ $question->category->name }} </a>
                </td>
                @if(count($question->tags))
                    <td style="max-width: 200px">
                        @foreach($question->tags as $tag)
                            <a href="{{ route('tag.edit', $tag->id) }}"><span> {{ $tag->name }}</span></a>
                            <span> , </span>
                        @endforeach
                    </td>
                @else
                    <td> -</td>
                @endif

                <td>
                    {!! Form::open(['route' => ['question.destroy', $question->id], 'method' => 'delete']) !!}
                    <div class="btn-group">
                        <a href="{!! route('question.show', [$question->id]) !!}" class="btn btn-default btn-xs"><i
                                    class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('question.edit', [$question->id]) !!}" class="btn btn-default btn-xs"><i
                                    class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>




@endsection