routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/home', 'HomeController@index');
//////////////////
Route::get('/', 'IndexController@index')->name('home');

Route::resource('tag', 'TagController');
Route::resource('category', 'CategoryController');
Route::resource('question', 'QuestionController');
Route::resource('answer', 'AnswerController');
Route::resource('comment', 'CommentController');

Route::resource('user', 'UserController');

Route::patch('answer/{answer}/votePositive', 'AnswerController@votePositive')->name('answer.positive');
Route::patch('answer/{answer}/voteNegative', 'AnswerController@voteNegative')->name('answer.negative');
Route::patch('question/{question}/votePositive', 'QuestionController@votePositive')->name('question.positive');// not completed
Route::patch('question/{question}/voteNegative', 'QuestionController@voteNegative')->name('question.negative');// not completed

Route::patch('answer/{answer}/bestAnswer', 'AnswerController@bestAnswer')->name('answer.best');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.layout')
@section('title', 'پرسش و پاسخ')
@section('content')

    @include('layouts.header')

    <div class="col-sm-10 col-sm-offset-1">
        <div class="row" style="padding: 30px">
            <a href="{{ route('question.create') }}" class="btn-primary btn">سوال بپرسید</a>
        </div>
        @foreach($questions as $question)
            <div class="row" style="padding: 10px;margin: 10px;border: 3px dashed gainsboro">
                <div class="col-sm-1" style="border-left: 1px dotted grey">
                    {{ $question->name }}
                </div>
                <div class="col-sm-11">
                    <a href="{{ route('question.show', $question->id) }}"><strong>{{ $question->title }}</strong></a>
                    <div style="font-size: x-small;color: #545454;">{{ $question->content }}</div>
                </div>
            </div>
        @endforeach
    </div>

    @include('layouts.footer')
@endsection